# Generated by Django 2.1.5 on 2019-01-28 13:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
                ('type', models.CharField(choices=[('O', 'ÔNIBUS'), ('C', 'CARRO'), ('V', 'VAN'), ('A', 'AMBULÂNCIA')], max_length=1, verbose_name='Tipo')),
                ('vacancy', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='N° de Vagas')),
                ('enable', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Município')),
                ('enable', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Feriado de')),
                ('date', models.DateField(unique=True, verbose_name='Dia')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns', models.CharField(blank=True, max_length=18, verbose_name='Cartão SUS')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('reference', models.CharField(blank=True, max_length=30, verbose_name='Referência')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Endereço')),
                ('local', models.CharField(blank=True, max_length=23, verbose_name='Destino')),
                ('date', models.DateField(blank=True, verbose_name='Data')),
                ('hour', models.TimeField(blank=True, choices=[(datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00')], default='07:00:00', verbose_name='Hora')),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('goal', models.CharField(blank=True, max_length=23, verbose_name='Finalidade')),
                ('search', models.CharField(blank=True, max_length=30, verbose_name='Local onde pegará o transporte')),
                ('note', models.CharField(blank=True, max_length=15, verbose_name='Observação')),
                ('companion', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, verbose_name='Acompanhante')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
                ('car', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.CarType', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Lista de Passageiros',
                'verbose_name_plural': 'Listas de Passageiros',
            },
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns', models.CharField(blank=True, max_length=18, verbose_name='Cartão SUS')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('reference', models.CharField(blank=True, max_length=30, verbose_name='Referência')),
                ('birth', models.CharField(blank=True, max_length=10, verbose_name='Data de Nascimento')),
                ('sex', models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=1, verbose_name='Sexo')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Endereço')),
                ('telephone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('enable', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_on', models.DateField(auto_now_add=True, verbose_name='Criado em:')),
                ('update_on', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
            ],
            options={
                'verbose_name': 'Cadastro de Usuário',
                'verbose_name_plural': 'Cadastro de Usuários',
            },
        ),
        migrations.AddField(
            model_name='cartype',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='Destino'),
        ),
    ]
