# Generated by Django 2.1.5 on 2019-01-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartype',
            options={'ordering': ('-type', 'destiny', 'description'), 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
    ]
